### ISSUE TITLE
Enhance - mermaid 渲染支持主题的明暗模式

### ISSUE THREAD

**Issue by jalr4ever** [xinkeng0/plugin-text-diagram#17]
# 问题

目前 mermaid 在暗色模式下渲染会看不清楚

暗色：
![Image](https://github.com/user-attachments/assets/647df2e8-78d2-42f5-9026-40f15b91533a)

亮色：
![Image](https://github.com/user-attachments/assets/98bb7424-e765-4180-9e1f-025895c8fa9d)

# 期望

支持类似 mermaid 官方那样，支持明暗色的良好渲染，插件侧把渲染工作做了，或者提供出接口让主题使用亮色或者暗色主题

亮色：
![Image](https://github.com/user-attachments/assets/d426e139-811b-415c-aef0-20a7a19482ef)

暗色：
![Image](https://github.com/user-attachments/assets/d9e70c53-fa28-490c-b4e3-b9ec4d3238f5)

**Comment by xinkeng0** [comment]
如果我们通过 [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme) 来查询用户的主题可以满足需求吗？
```javascript
let matchResult = window.matchMedia('(prefers-color-scheme: dark)');
mermaid.initialize({
  theme: matchResult?'dark':'default',
});
```

**Comment by jalr4ever** [comment]
> 如果我们通过 [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme) 来查询用户的主题可以满足需求吗？
> 
> let matchResult = window.matchMedia('(prefers-color-scheme: dark)');
> mermaid.initialize({
>   theme: matchResult?'dark':'default',
> });

@HowieHz 有请专业前端评估一下

**Comment by HowieHz** [comment]
> > 如果我们通过 [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme) 来查询用户的主题可以满足需求吗？
> > let matchResult = window.matchMedia('(prefers-color-scheme: dark)');
> > mermaid.initialize({
> > theme: matchResult?'dark':'default',
> > });
> 
> [@HowieHz](https://github.com/HowieHz) 有请专业前端评估一下

不专业的说点看法:
1. 简单实现（不能满足需求，如切换主题配色的按钮）：插件配置项允许用户选择：明/暗/自动
2. 复杂实现a：插件提供方法能让主题去适配，这样主题作者就能像 https://docs.halo.run/developer-guide/theme/finder-apis/plugin  来调用某个方法设置 mermaid theme
3. 复杂实现b：如同 [官方评论组件](https://github.com/halo-dev/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D) 通过定义 CSS 变量的方式为评论组件提供动态切换配色的功能
4. 复杂实现c：直接复用 官方评论组件指定的 class 和 data-color-scheme 属性 检查方式 
> 截图来自 [官方评论组件 Readme](https://github.com/halo-dev/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D) 
 > ![Image](https://github.com/user-attachments/assets/91e78357-cb1d-457c-82c6-bdfcb480630c)

复杂实现 a、b、c 能实现一个就行，个人倾向 c 先实现，适配也方便（套用现有适配评论组件的方式）。
如果可以就实现下 b 提供更多可能，就是要查阅下 mermaid 支持的属性工作量更大。

**Comment by xinkeng0** [comment]
> > > 如果我们通过 [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme) 来查询用户的主题可以满足需求吗？
> > > let matchResult = window.matchMedia('(prefers-color-scheme: dark)');
> > > mermaid.initialize({
> > > theme: matchResult?'dark':'default',主题: matchResult?'dark':'default',
> > > });
> > 
> > 
> > [@HowieHz](https://github.com/HowieHz) 有请专业前端评估一下
> 
> 不专业的说点看法:
> 
> 1. 简单实现（不能满足需求，如切换主题配色的按钮）：插件配置项允许用户选择：明/暗/自动
> 2. 复杂实现a：插件提供方法能让主题去适配，这样主题作者就能像 https://docs.halo.run/developer-guide/theme/finder-apis/plugin  来调用某个方法设置 mermaid theme
> 3. 复杂实现b：如同 [官方评论组件](https://github.com/halo-dev/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D) 通过定义 CSS 变量的方式为评论组件提供动态切换配色的功能
> 4. 复杂实现c：直接复用 官方评论组件指定的 class 和 data-color-scheme 属性 检查方式
> 
> > 截图来自 [官方评论组件 Readme](https://github.com/halo-dev/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D)
> > ![Image](https://github.com/user-attachments/assets/91e78357-cb1d-457c-82c6-bdfcb480630c)
> 
> 复杂实现 a、b、c 能实现一个就行，个人倾向 c 先实现，适配也方便（套用现有适配评论组件的方式）。 如果可以就实现下 b 提供更多可能，就是要查阅下 mermaid 支持的属性工作量更大。

检查[mermaid#theme](https://mermaid.js.org/config/theming.html#available-themes)这里，mermaid主题的配置并非通过 [Using_CSS_custom_properties](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_custom_properties)实现，所以我们还是需要去寻找一种方式（可以去检测用户的主题色设置），一方面来说我们是否要遵循prefers-color-scheme的标准定义，其次我们也可以来约定一个标准的class来表示dark或normal

**Comment by xinkeng0** [comment]
![Image](https://github.com/user-attachments/assets/62cc387e-b9af-4e52-8d82-ae0d5e93d3d1)
目前来看1,2都是一个不错的选择

**Comment by HowieHz** [comment]
> > > > 如果我们通过 [prefers-color-scheme](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@media/prefers-color-scheme) 来查询用户的主题可以满足需求吗？
> > > > let matchResult = window.matchMedia('(prefers-color-scheme: dark)');
> > > > mermaid.initialize({
> > > > theme: matchResult?'dark':'default',主题: matchResult?'dark':'default',
> > > > });
> > > 
> > > 
> > > [@HowieHz](https://github.com/HowieHz) 有请专业前端评估一下
> > 
> > 
> > 不专业的说点看法:
> > 
> > 1. 简单实现（不能满足需求，如切换主题配色的按钮）：插件配置项允许用户选择：明/暗/自动
> > 2. 复杂实现a：插件提供方法能让主题去适配，这样主题作者就能像 https://docs.halo.run/developer-guide/theme/finder-apis/plugin  来调用某个方法设置 mermaid theme
> > 3. 复杂实现b：如同 [官方评论组件](https://github.com/halo-dev/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D) 通过定义 CSS 变量的方式为评论组件提供动态切换配色的功能
> > 4. 复杂实现c：直接复用 官方评论组件指定的 class 和 data-color-scheme 属性 检查方式
> > 
> > > 截图来自 [官方评论组件 Readme](https://github.com/halo-dev/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D)
> > > ![Image](https://github.com/user-attachments/assets/91e78357-cb1d-457c-82c6-bdfcb480630c)
> > 
> > 
> > 复杂实现 a、b、c 能实现一个就行，个人倾向 c 先实现，适配也方便（套用现有适配评论组件的方式）。 如果可以就实现下 b 提供更多可能，就是要查阅下 mermaid 支持的属性工作量更大。
> 
> 检查[mermaid#theme](https://mermaid.js.org/config/theming.html#available-themes)这里，mermaid主题的配置并非通过 [Using_CSS_custom_properties](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_custom_properties)实现，所以我们还是需要去寻找一种方式（可以去检测用户的主题色设置），一方面来说我们是否要遵循prefers-color-scheme的标准定义，其次我们也可以来约定一个标准的class来表示dark或normal

可以提供选项，设定 mermaid theme 遵循的模式
三个大选项

1. 强制设定主题模式（使用场景：按喜好强制设定/没有任何明暗设定的主题/没有适配的主题）
  - [default](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/themes/theme-default.js)
  - [neutral](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/themes/theme-neutral.js)
  - [dark](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/themes/theme-dark.js)
  - [forest](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/themes/theme-forest.js)
  - [base](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/themes/theme-base.js)
     - 启用这个之后允许指定 [#theme-variables](https://mermaid.js.org/config/theming.html#theme-variables) （文档强调了要 base theme 才能应用这个 [#customizing-themes-with-themevariables](https://mermaid.js.org/config/theming.html#customizing-themes-with-themevariables)
2. 自动调节模式（遵循 prefers-color-scheme 设定）（使用场景：遵循 prefers-color-scheme 自动设定明暗的主题/没有适配的主题）
3. 检查 class 和 data-color-scheme 来自动设定主题（使用场景：使用对这个插件进行适配的主题）

**Comment by xinkeng0** [comment]
试试看 https://github.com/halo-sigs/plugin-text-diagram/releases/tag/v1.4.0

**Comment by HowieHz** [comment]
> 试试看 https://github.com/halo-sigs/plugin-text-diagram/releases/tag/v1.4.0

有构建好的包吗，我懒得拉取然后构建了。我看 github action 好像 failed 了

**Comment by xinkeng0** [comment]
> > 试试看 https://github.com/halo-sigs/plugin-text-diagram/releases/tag/v1.4.0
> 
> 有构建好的包吗，我懒得拉取然后构建了。我看 github action 好像 failed 了

releases里有构建好的包了，appStrore似乎上传失败了。

**Comment by xinkeng0** [comment]
> 试试看 https://github.com/halo-sigs/plugin-text-diagram/releases/tag/v1.4.0

有任何人测试过它吗？效果如何？

**Comment by HowieHz** [comment]
> > 试试看 https://github.com/halo-sigs/plugin-text-diagram/releases/tag/v1.4.0
> 
> 有任何人测试过它吗？效果如何？

不能像官方评论区一样 work
![Image](https://github.com/user-attachments/assets/d5e5584e-7edd-4b08-8bf2-9a97fb2a0c6e)

**Comment by xinkeng0** [comment]
> 不能像官方评论区一样 work 

@HowieHz 暂不支持页面中动态切换主题，配置可以参考这里：https://github.com/halo-sigs/plugin-text-diagram?tab=readme-ov-file#%E6%96%87%E7%AB%A0%E9%A1%B5%E6%B8%B2%E6%9F%93

**Comment by HowieHz** [comment]
> > 不能像官方评论区一样 work
> 
> [@HowieHz](https://github.com/HowieHz) 暂不支持页面中动态切换主题，配置可以参考这里：https://github.com/halo-sigs/plugin-text-diagram?tab=readme-ov-file#%E6%96%87%E7%AB%A0%E9%A1%B5%E6%B8%B2%E6%9F%93

嗯，实时刷新不行，但是切换到黑色然后f5一下能正常加载

**Comment by HowieHz** [comment]
插件配置为 `html[class~=dark],html[data-color-scheme=dark]`
![Image](https://github.com/user-attachments/assets/d1f14599-60df-49e4-9a5e-270628608e77)

**Comment by jalr4ever** [comment]
所以这个的结论是啥，主题那一侧有集成方案么？ @HowieHz

**Comment by xinkeng0** [comment]
> 所以这个的结论是啥，主题那一侧有集成方案么？ @HowieHz 

@jalr4ever 升级到1.4即可，插件这边支持

**Comment by HowieHz** [comment]
> > 所以这个的结论是啥，主题那一侧有集成方案么？ [@HowieHz](https://github.com/HowieHz)
> 
> [@jalr4ever](https://github.com/jalr4ever) 升级到1.4即可，插件这边支持

希望支持下动态明暗切换，我不会改插件，所以没法提 pr，

和 @jalr4ever 交流后，决定两周前先在主题那边内嵌支持了

https://github.com/HowieHz/halo-theme-higan-hz/releases/tag/v1.16.0
https://github.com/HowieHz/halo-theme-higan-hz/compare/v1.15.1...v1.16.0

原理来说就是渲染两遍，然后用 css 决定是否显示其中一种

渲染两遍图的时候也要注意 [id 冲突](https://github.com/HowieHz/halo-theme-higan-hz/releases/tag/v1.16.1)的问题
