### ISSUE TITLE
feat: Choosing an implementation solution for PlantUML

### ISSUE THREAD

**Issue by xinkeng0** [xinkeng0/plugin-text-diagram#7]
Since version 1.0, this plugin has been able to support PlantUML and Mermaid. However, I have some thoughts on the implementation of PlantUML.

The current implementation method is pure JavaScript, which requires dependency on a PlantUML server (official server).
- https://plantuml.com/en/code-javascript-asynchronous

I believe there are several ways to improve:

1. Retain the current implementation method, but allow users to utilize their own PlantUML server.
We simply need to use ServerUrl as a plugin configuration item.

2. Employ [plantuml.js](https://github.com/plantuml/plantuml.js) to operate entirely on the browser without the need for a server.
    > PlantUML that operates entirely on the browser without the need for a server.

   Technically, this is not an issue as I have constructed a well-functioning demo based on this library. The challenge in choosing this solution is that it relies on a Java virtual machine called [CheerJ](https://labs.leaningtech.com/cheerpj3) to function.This may be overly complex for the end user.
    > CheerpJ is a WebAssembly-based Java Virtual Machine for the browser. It has extensive compatibility with Java 8 and provides a full runtime environment[1](https://labs.leaningtech.com/cheerpj3#user-content-fn-compat) for running Java applications, applets, libraries, and Java Web Start / JNLP applications in the browser without plugins.

- https://github.com/halo-dev/halo/discussions/4791#discussioncomment-8105015

**Comment by xinkeng0** [comment]
Speaking solely from my personal perspective, I am more inclined towards Plan 1.
Because for now, it’s simple enough.

**Comment by ruibaby** [comment]
> Speaking solely from my personal perspective, I am more inclined towards Plan 1. Because for now, it’s simple enough.

+1
